apiVersion: v1
kind: Pod
metadata:
  name: shared-pod
spec:
  containers:
  - name: writer
    image: busybox
    command: ["sh", "-c", "echo Hi > /data/message.txt; sleep 3600"]
    volumeMounts:
    - name: shared-directory
      mountPath: /data
  - name: reader
    image: busybox
    command: ["sh", "-c", "cat /data/message.txt; sleep 3600"]
    volumeMounts:
    - name: shared-directory
      mountPath: /data
  volumes:
  - name: shared-directory
    emptyDir: {}
