apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      lebels:
        app: api
    spec:
      containers:
      - name: httpd
        image: httpsd:2.4
        ports:
        - contianerPort: 80
